version: "3.9"
services:
  database:
    image: mariadb:10.8.3-jammy
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: artinaut
      MYSQL_USER: artinaut
      MYSQL_PASSWORD: secret
      TZ: "Europe/Zurich"
      MARIADB_AUTO_UPGRADE: "true"
    tmpfs:
      - /var/lib/mysql:rw
    ports:
      - "127.0.0.1:3306:3306"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 200M

  artinaut:
    image: ghcr.io/saw303/artinaut/artinaut:0.1.2
    environment:
      DB_HOST: database
      DB_NAME: artinaut
      DB_USER: artinaut
      DB_PWD: secret
      ARTINAUT_FILESTORE: /home/app/filestore
    ports:
      - "127.0.0.1:8080:8080"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 200M


